name: apiverve_guidgenerator
description: GUID Generator is a tool for generating Globally Unique Identifiers (GUIDs). It creates RFC 4122 version 4 UUIDs with multiple formatting options including uppercase, no hyphens, and braces.
version: 1.1.14
homepage: https://apiverve.com/marketplace/guidgenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/guidgenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
